DELIMITER $$
CREATE PROCEDURE INSERT_UPDATE_CLIENTE(
  IN VAR_USUARIO_ID INT,
  IN VAR_NOME VARCHAR(50),
  IN VAR_CPF_CNPJ VARCHAR(14),
  IN VAR_EMPRESA_ID INT
)

BEGIN
  
  IF VAR_USUARIO_ID IS NULL THEN
    INSERT INTO USUARIO (NOME, CPF_CNPJ, EMPRESA_ID)
    VALUES (VAR_NOME, VAR_CPF_CNPJ, VAR_EMPRESA_ID);
    
    SET VAR_USUARIO_ID = LAST_INSERT_ID();
  ELSE
    UPDATE USUARIO
    SET 
      NOME = VAR_NOME, 
      CPF_CNPJ = VAR_CPF_CNPJ;
   
  END IF;
END;
$$
DELIMITER ;
