DELIMITER $$
CREATE PROCEDURE INSERT_UPDATE_VEICULO(
  IN VAR_USUARIO_ID INT,
  IN VAR_PLACA VARCHAR(7),
  IN VAR_MODELO VARCHAR(30),
  IN VAR_MARCA VARCHAR(30)
)

BEGIN
  
  DECLARE VAR_VEICULO_ID INT;
  
  SELECT
    VEICULO_ID INTO VAR_VEICULO_ID
  FROM VEICULO
  WHERE MARCA = VAR_MARCA
  AND MODELO = VAR_MODELO;
  
  IF VAR_VEICULO_ID IS NULL THEN
    INSERT INTO VEICULO (MODELO, MARCA)
    VALUES (VAR_MODELO, VAR_MARCA);
    
    SET VAR_VEICULO_ID = LAST_INSERT_ID();
  END IF;
  
  INSERT IGNORE INTO VEICULO_USUARIO(VEICULO_ID, USUARIO_ID, PLACA)
  VALUES (VAR_VEICULO_ID, VAR_USUARIO_ID, VAR_PLACA);
  
END;
$$
DELIMITER ;
