CREATE TABLE ADMIN(
	USUARIO_ID INT,
	LOGIN VARCHAR(50),
  SENHA VARCHAR(255),
	CONSTRAINT PK_ADMIN PRIMARY KEY (USUARIO_ID),
	CONSTRAINT FK_ADMIN_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);