CREATE TABLE BOX_VAGA(
	EMPRESA_ID INT,
	USUARIO_ID INT,
    VEICULO_USUARIO_ID INT,
	CODIGO VARCHAR(20) NOT NULL,
	VAGA INT NOT NULL,
	RESERVADA BOOLEAN DEFAULT FALSE,
	DATA_HORA_ULT_ENTRADA TIMESTAMP(6) NULL,
	DATA_HORA_ULT_SAIDA TIMESTAMP(6) NULL,
	CONSTRAINT PK_BOX_VAGA PRIMARY KEY (EMPRESA_ID, CODIGO, VAGA),
	CONSTRAINT FK_BOX_VAGA_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(EMPRESA_ID),
    CONSTRAINT FK_BOX_VAGA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
	CONSTRAINT FK_BOX_VAGA_VEICULO_USUARIO FOREIGN KEY (VEICULO_USUARIO_ID) REFERENCES VEICULO_USUARIO(VEICULO_USUARIO_ID)
);
