CREATE TABLE BOX_VAGA(
	EMPRESA_ID INT,
	CODIGO VARCHAR(1),
	VAGA TINYINT(1),
  RESERVADA BOOLEAN DEFAULT FALSE,
	DATA_HORA_ULT_ENTRADA TIMESTAMP(6) NULL,
	DATA_HORA_ULT_SAIDA TIMESTAMP(6) NULL,
	CONSTRAINT PK_BOX_VAGA PRIMARY KEY (EMPRESA_ID, CODIGO, VAGA),
  CONSTRAINT FK_BOX_VAGA_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(EMPRESA_ID)
);
