CREATE TABLE EMAIL_EMPRESA(
  EMAIL_ID INT,
  EMPRESA_ID INT NOT NULL,
  CONSTRAINT PK_EMAIL_EMPRESA PRIMARY KEY (EMAIL_ID),
  CONSTRAINT FK_EMAIL_EMPRESA_EMAIL FOREIGN KEY (EMAIL_ID) REFERENCES EMAIL(EMAIL_ID),
  CONSTRAINT FK_EMAIL_EMPRESA_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(EMPRESA_ID)
);