CREATE TABLE ENDERECO(
  ENDERECO_ID INT AUTO_INCREMENT,
  TIPO TINYINT(1) COMMENT '0 = Comercial; 1 = Residencial;' DEFAULT  0 CHECK (TIPO IN (0,1)),
  CEP INT(9),
  LOGRADOURO VARCHAR(50),
  NUMERO INT,
  COMPLEMENTO VARCHAR(50),
  BAIRRO VARCHAR(50),
  CIDADE_ID INT NOT NULL,
  ESTADO_ID INT NOT NULL,
  CONSTRAINT PK_ENDERECO PRIMARY KEY (ENDERECO_ID),
  CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE(CIDADE_ID),
  CONSTRAINT FK_ENDERECO_ESTADO FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ESTADO_ID)
);
