CREATE TABLE ENDERECO_USUARIO(
  ENDERECO_ID INT,
  USUARIO_ID INT,
  CONSTRAINT PK_ENDERECO_USUARIO PRIMARY KEY (ENDERECO_ID),
  CONSTRAINT FK_ENDERECO_USUARIO_ENDERECO FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ENDERECO_ID),
  CONSTRAINT FK_ENDERECO_USUARIO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);