CREATE TABLE ENDERECO(
  ENDERECO_ID INT AUTO_INCREMENT,
  TIPO TINYINT(1) COMMENT '0 = Comercial; 1 = Residencial;' DEFAULT  0 CHECK (TIPO IN (0,1)),
  CEP INT(9),
  LOGRADOURO VARCHAR(50),
  NUMERO INT,
  COMPLEMENTO VARCHAR(50),
  BAIRRO VARCHAR(50),
  CIDADE VARCHAR(50),
  UF VARCHAR(2) CHECK (UF IN ('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO')),
  CONSTRAINT PK_ENDERECO PRIMARY KEY (ENDERECO_ID)
);
