CREATE TABLE ENDERECO_EMPRESA(
  ENDERECO_ID INT,
  EMPRESA_ID INT,
  CONSTRAINT PK_ENDERECO_EMPRESA PRIMARY KEY (ENDERECO_ID),
  CONSTRAINT FK_ENDERECO_EMPRESA_ENDERECO FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ENDERECO_ID),
  CONSTRAINT FK_ENDERECO_EMPRESA_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(EMPRESA_ID)
);