CREATE TABLE FUNCIONARIO(
	USUARIO_ID INT,
	LOGIN VARCHAR(50),
  SENHA VARCHAR(255),
	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (USUARIO_ID),
	CONSTRAINT FK_FUNCIONARIO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);