CREATE TABLE MENSALIDADE(
  MENSALIDADE_ID INT AUTO_INCREMENT,
  USUARIO_ID INT,
  VALOR_MENSALIDADE DOUBLE,
  DATA_INICIO TIMESTAMP,
  DIA_VENCIMENTO INT,
  CONSTRAINT PK_MENSALIDADE PRIMARY KEY (MENSALIDADE_ID),
  CONSTRAINT FK_MENSALIDADE_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

