CREATE TABLE MENSALIDADE(
  MENSALIDADE_ID INT AUTO_INCREMENT,
  USUARIO_ID INT NOT NULL,
  VALOR_MENSALIDADE DOUBLE NOT NULL,
  DATA_INICIO TIMESTAMP DEFAULT CURRENT_TIME,
  DIA_VENCIMENTO INT DEFAULT 1,
  CONSTRAINT PK_MENSALIDADE PRIMARY KEY (MENSALIDADE_ID),
  CONSTRAINT FK_MENSALIDADE_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

