CREATE TABLE PAGAMENTO(
  PAGAMENTO_ID INT AUTO_INCREMENT,
  USUARIO_ID INT NOT NULL,
  VALOR DOUBLE NOT NULL,
  DATA_PAGAMENTO TIMESTAMP CURRENT_TIME,
  CONSTRAINT PK_PAGAMENTO PRIMARY KEY (PAGAMENTO_ID),
  CONSTRAINT FK_PAGAMENTO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

