CREATE TABLE PAGAMENTO(
  PAGAMENTO_ID INT AUTO_INCREMENT,
  USUARIO_ID INT,
  VALOR DOUBLE,
  DATA_PAGAMENTO TIMESTAMP,
  CONSTRAINT PK_PAGAMENTO PRIMARY KEY (PAGAMENTO_ID),
  CONSTRAINT FK_PAGAMENTO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

