CREATE TABLE TELEFONE_USUARIO(
	TELEFONE_ID INT,
	USUARIO_ID INT NOT NULL,
	CONSTRAINT PK_TELEFONE_USUARIO PRIMARY KEY (TELEFONE_ID),
	CONSTRAINT FK_TELEFONE_USUARIO_TELEFONE FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONE(TELEFONE_ID),
	CONSTRAINT FK_TELEFONE_USUARIO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);