CREATE TABLE USUARIO(
  USUARIO_ID INT AUTO_INCREMENT,
  TIPO TINYINT COMMENT'0 = CLIENTE; 1 = FUNCIONARIO; 2 = ADMIN'  DEFAULT 0 CHECK(TIPO IN(0,1,2)),
  NOME VARCHAR(50),
  CPF_CNPJ INT(14),
  CONSTRAINT PK_USUARIO PRIMARY KEY (USUARIO_ID)
);
