CREATE TABLE USUARIO_LOGIN(
	USUARIO_ID INT,
	LOGIN VARCHAR(50) UNIQUE NOT NULL,
	SENHA VARCHAR(255) NOT NULL,
  ATIVO TINYINT COMMENT '0 = Ativo; 1 = Inativo;' DEFAULT  0 CHECK (TIPO IN (0,1)),
	CONSTRAINT PK_USUARIO_LOGIN PRIMARY KEY (USUARIO_ID),
	CONSTRAINT FK_USUARIO_LOGIN_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);