CREATE TABLE USUARIO_LOGIN(
	USUARIO_ID INT,
	LOGIN VARCHAR(50) NOT NULL,
	SENHA VARCHAR(255) NOT NULL,
	CONSTRAINT PK_USUARIO_LOGIN PRIMARY KEY (USUARIO_ID),
	CONSTRAINT FK_USUARIO_LOGIN_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);