CREATE TABLE VEICULO_USUARIO(
  VEICULO_USUARIO_ID INT AUTO_INCREMENT,
	VEICULO_ID INT,
  USUARIO_ID INT NOT NULL,
  PLACA VARCHAR(7) UNIQUE,
  CONSTRAINT PK_VEICULO_USUARIO PRIMARY KEY (VEICULO_USUARIO_ID),
  CONSTRAINT FK_VEICULO_USUARIO_VEICULO FOREIGN KEY (VEICULO_ID) REFERENCES VEICULO(VEICULO_ID),
  CONSTRAINT FK_VEICULO_USUARIO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

