CREATE TABLE VEICULO_USUARIO(
	VEICULO_ID INT,
  USUARIO_ID INT NOT NULL,
  PLACA VARCHAR(7) UNIQUE,
  CONSTRAINT FK_VEICULO_USUARIO_VEICULO FOREIGN KEY (VEICULO_ID) REFERENCES VEICULO(VEICULO_ID),
  CONSTRAINT FK_VEICULO_USUARIO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

